---
- name: "Import validator"
  ansible.builtin.import_tasks: 'validator/main.yml'
  tags:
    - always

- name: 'Import openssh'
  ansible.builtin.import_tasks: 'openssh/main.yml'
  tags:
    - openssh
  when: openssh_config

- name: 'Import kernel hardening'
  ansible.builtin.import_tasks: 'hardening/kernel.yml'
  when: kernel_hardening
  tags:
    - hardening
    - kernel_hardening

- name: 'Import network hardening'
  ansible.builtin.import_tasks: 'hardening/network.yml'
  when: network_hardening
  tags:
    - hardening
    - network_hardening
