---

- name: "import validator"
  ansible.builtin.import_tasks: 'validator/main.yml'
  tags:
    - always

- name: 'import openssh'
  ansible.builtin.import_tasks: 'openssh/main.yml'
  when: openssh_config
