---

- name: "import validator"
  ansible.builtin.import_tasks: 'validator/main.yml'
  tags:
    - always

- name: 'import openssh'
  ansible.builtin.import_tasks: 'openssh/main.yml'
  when: openssh_config

- name: 'import kernel hardening'
  ansible.builtin.import_tasks: 'hardening/kernel.yml'
  when: kernel_hardening

- name: 'import network hardening'
  ansible.builtin.import_tasks: 'hardening/network.yml'
  when: network_hardening
