---
- name: 'Import preconfigure tasks'
  ansible.builtin.import_tasks: openssh/preconfigure.yml
  tags:
    - install
    - openssh_install

- name: 'Import configure tasks'
  ansible.builtin.import_tasks: openssh/configure.yml
  tags:
    - install
    - configure
    - openssh_install
    - openssh_configure
