---
- name: 'openssh | preconfigure | remove existing host keys'
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/ssh/ssh_host_ecdsa_key'
    - '/etc/ssh/ssh_host_ecdsa_key.pub'
    - '/etc/ssh/ssh_host_ed25519_key'
    - '/etc/ssh/ssh_host_ed25519_key.pub'
    - '/etc/ssh/ssh_host_rsa_key'
    - '/etc/ssh/ssh_host_rsa_key.pub'

- name: 'openssh | preconfigure | generate new host keys'
  community.crypto.openssh_keypair:
    path: '{{ item.path }}'
    type: '{{ item.type }}'
    size: '{{ item.size }}'
    comment: "SSH {{ item.type }} key for {{ ansible_hostname }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - { path: '/etc/ssh/ssh_host_rsa_key', type: 'rsa', size: 4096 }
    - { path: '/etc/ssh/ssh_host_ed25519_key', type: 'ed25519', size: 256 }
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 17) or

- name: 'openssh | preconfigure | enable systemd targets on RHEL based system'
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - 'sshd-keygen@rsa.service'
    - 'sshd-keygen@ed25519.service'
  when: (ansible_distribution == 'Rocky' and ansible_distribution_major_version|int >= 8) or
        (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8)
