---
- name: 'OpenSSH | Preconfigure | remove existing host keys'
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/ssh/ssh_host_ecdsa_key'
    - '/etc/ssh/ssh_host_ecdsa_key.pub'

- name: 'OpenSSH | Preconfigure | generate new ed25519 host keys'
  community.crypto.openssh_keypair:
    path: '/etc/ssh/ssh_host_ed25519_key'
    backend: 'opensshbin'
    type: 'ed25519'
    owner: 'root'
    group: 'root'
    mode: '0600'
    regenerate: full_idempotence

- name: 'OpenSSH | Preconfigure | generate new rsa host keys'
  community.crypto.openssh_keypair:
    path: '/etc/ssh/ssh_host_rsa_key'
    type: 'rsa'
    size: 4096
    owner: 'root'
    group: 'root'
    mode: '0600'
    regenerate: full_idempotence

- name: 'OpenSSH | Preconfigure | rocky linux tasks'
  block:
    - name: 'OpenSSH | Preconfigure | stat if crypto policy configuration exist'
      ansible.builtin.stat:
        path: '/etc/crypto-policies/back-ends/opensshserver.config'
      register: crypto_policy_state

    - name: 'OpenSSH | Preconfigure | disable rocky linux openssh crypto policy'
      ansible.builtin.lineinfile:
        path: '/etc/crypto-policies/back-ends/opensshserver.config'
        regexp: "^CRYPTO_POLICY='.*"
        line: "CRYPTO_POLICY=''"
      when: crypto_policy_state.stat.exists

    - name: 'OpenSSH | Preconfigure | disable ssh host key generation services'
      ansible.builtin.systemd:
        name: '{{ item }}'
        state: stopped
        masked: yes
        enabled: no
      with_items:
        - 'sshd-keygen@rsa.service'
        - 'sshd-keygen@ed25519.service'
        - 'sshd-keygen@ecdsa.service'

    - name: 'OpenSSH | Preconfigure | revalidate selinux files fingerprint'
      ansible.builtin.command: restorecon -irv /etc/ssh/

  when: ansible_distribution == 'Rocky' and ansible_distribution_major_version|int >= 8
